## Importing Liberaries

In [1]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("WebAgg")
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
import sklearn.metrics as sm
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import pickle

## Reading Data

In [2]:
df = pd.read_csv("loan_data.csv")

In [3]:
df

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   credit.policy      9578 non-null   int64  
 1   purpose            9578 non-null   object 
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64  
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64  
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64  
 11  delinq.2yrs        9578 non-null   int64  
 12  pub.rec            9578 non-null   int64  
 13  not.fully.paid     9578 non-null   int64  
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB


## Check Null Values

In [5]:
df.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [6]:
df.describe()

credit.policy     int.rate  installment  log.annual.inc          dti  \
count    9578.000000  9578.000000  9578.000000     9578.000000  9578.000000   
mean        0.804970     0.122640   319.089413       10.932117    12.606679   
std         0.396245     0.026847   207.071301        0.614813     6.883970   
min         0.000000     0.060000    15.670000        7.547502     0.000000   
25%         1.000000     0.103900   163.770000       10.558414     7.212500   
50%         1.000000     0.122100   268.950000       10.928884    12.665000   
75%         1.000000     0.140700   432.762500       11.291293    17.950000   
max         1.000000     0.216400   940.140000       14.528354    29.960000   

              fico  days.with.cr.line     revol.bal   revol.util  \
count  9578.000000        9578.000000  9.578000e+03  9578.000000   
mean    710.846314        4560.767197  1.691396e+04    46.799236   
std      37.970537        2496.930377  3.375619e+04    29.014417   
min     612.000000         178.958333  0.000000e+00     0.000000   
25%     682.000000        2820.000000  3.187000e+03    22.600000   
50%     707.000000        4139.958333  8.596000e+03    46.300000   
75%     737.000000        5730.000000  1.824950e+04    70.900000   
max     827.000000       17639.958330  1.207359e+06   119.000000   

       inq.last.6mths  delinq.2yrs      pub.rec  not.fully.paid  
count     9578.000000  9578.000000  9578.000000     9578.000000  
mean         1.577469     0.163708     0.062122        0.160054  
std          2.200245     0.546215     0.262126        0.366676  
min          0.000000     0.000000     0.000000        0.000000  
25%          0.000000     0.000000     0.000000        0.000000  
50%          1.000000     0.000000     0.000000        0.000000  
75%          2.000000     0.000000     0.000000        0.000000  
max         33.000000    13.000000     5.000000        1.000000

## Label Encoding

In [7]:
df["purpose"].unique()

array(['debt_consolidation', 'credit_card', 'all_other',
       'home_improvement', 'small_business', 'major_purchase',
       'educational'], dtype=object)

In [8]:
encode = LabelEncoder()

In [9]:
df["purpose"] = encode.fit_transform(df["purpose"])

In [10]:
df["purpose"].unique()

array([2, 1, 0, 4, 6, 5, 3])

## Check Correlation Between Features

In [11]:
plt.figure(figsize=(12,10))
cor = df.corr()
sns.heatmap(cor, annot=True, cmap = plt.cm.CMRmap_r)
plt.show()

Press Ctrl+C to stop WebAgg server


RuntimeError: This event loop is already running

## Standard Scaling

In [12]:
scaler = StandardScaler()

In [13]:
x = df.drop(columns = "not.fully.paid")

In [14]:
result = scaler.fit_transform(x)

In [15]:
result

array([[ 0.49222226,  0.03317632, -0.13931753, ..., -0.71698894,
        -0.29973008, -0.23700318],
       [ 0.49222226, -0.55966463, -0.57886837, ..., -0.71698894,
        -0.29973008, -0.23700318],
       [ 0.49222226,  0.03317632,  0.48648368, ..., -0.26247044,
        -0.29973008, -0.23700318],
       ...,
       [-2.03160257,  0.03317632, -0.57886837, ...,  2.91915909,
        -0.29973008, -0.23700318],
       [-2.03160257,  1.2188582 ,  1.39166043, ...,  1.55560358,
        -0.29973008, -0.23700318],
       [-2.03160257,  0.03317632,  0.61685894, ...,  2.01012208,
        -0.29973008, -0.23700318]])

In [16]:
x_scaler = pd.DataFrame(result, columns=x.columns)

In [17]:
x_scaler.describe()

credit.policy       purpose      int.rate   installment  \
count   9.578000e+03  9.578000e+03  9.578000e+03  9.578000e+03   
mean   -9.495664e-17  4.896202e-17 -4.747832e-17 -4.896202e-17   
std     1.000052e+00  1.000052e+00  1.000052e+00  1.000052e+00   
min    -2.031603e+00 -1.152506e+00 -2.333347e+00 -1.465366e+00   
25%     4.922223e-01 -5.596646e-01 -6.980686e-01 -7.501161e-01   
50%     4.922223e-01  3.317632e-02 -2.011729e-02 -2.421486e-01   
75%     4.922223e-01  3.317632e-02  6.727340e-01  5.489849e-01   
max     4.922223e-01  2.404540e+00  3.492564e+00  2.999368e+00   

       log.annual.inc           dti          fico  days.with.cr.line  \
count    9.578000e+03  9.578000e+03  9.578000e+03       9.578000e+03   
mean     1.348681e-15 -7.121748e-17  2.848699e-16      -5.934790e-17   
std      1.000052e+00  1.000052e+00  1.000052e+00       1.000052e+00   
min     -5.505403e+00 -1.831405e+00 -2.603373e+00      -1.754970e+00   
25%     -6.078650e-01 -7.836264e-01 -7.597422e-01      -6.971993e-01   
50%     -5.259710e-03  8.472466e-03 -1.013026e-01      -1.685393e-01   
75%      5.842340e-01  7.762382e-01  6.888249e-01       4.682925e-01   
max      5.849627e+00  2.520962e+00  3.059207e+00       5.238382e+00   

          revol.bal    revol.util  inq.last.6mths   delinq.2yrs       pub.rec  
count  9.578000e+03  9.578000e+03    9.578000e+03  9.578000e+03  9.578000e+03  
mean  -1.186958e-17  4.154353e-17    2.373916e-17  1.186958e-17  5.638051e-17  
std    1.000052e+00  1.000052e+00    1.000052e+00  1.000052e+00  1.000052e+00  
min   -5.010888e-01 -1.613049e+00   -7.169889e-01 -2.997301e-01 -2.370032e-01  
25%   -4.066715e-01 -8.340853e-01   -7.169889e-01 -2.997301e-01 -2.370032e-01  
50%   -2.464259e-01 -1.720737e-02   -2.624704e-01 -2.997301e-01 -2.370032e-01  
75%    3.956625e-02  8.306913e-01    1.920481e-01 -2.997301e-01 -2.370032e-01  
max    3.526782e+01  2.488574e+00    1.428212e+01  2.350167e+01  1.883877e+01

In [18]:
x_scaler["not.fully.paid"] = df["not.fully.paid"]

## Check VIF Score of Features

In [19]:
vif = pd.DataFrame()
vif['VIF'] = [variance_inflation_factor(x_scaler.values, i) for i in range(x_scaler.shape[1])]
vif['variable'] = x_scaler.columns
print(vif)

         VIF           variable
0   1.667380      credit.policy
1   1.073101            purpose
2   2.836731           int.rate
3   1.609075        installment
4   1.535681     log.annual.inc
5   1.200531                dti
6   3.363273               fico
7   1.305372  days.with.cr.line
8   1.367487          revol.bal
9   1.734463         revol.util
10  1.466583     inq.last.6mths
11  1.140323        delinq.2yrs
12  1.049257            pub.rec
13  1.047676     not.fully.paid


## Handeling Outliers

In [20]:
fig,ax = plt.subplots()
plt.figure(figsize=(40,80))
sns.boxplot(data = x_scaler, ax = ax)
plt.show()

In [21]:
q = x_scaler[x_scaler.columns[7]].quantile(.94)
df_new = x_scaler[x_scaler[x_scaler.columns[7]]<q]

In [22]:
q = df_new[df_new.columns[4]].quantile(.98)
df_new = df_new[df_new[df_new.columns[4]]<q]

q = df_new[df_new.columns[4]].quantile(.98)
df_new = df_new[df_new[df_new.columns[4]]> -q]

In [23]:
q = df_new[df_new.columns[11]].quantile(.98)
df_new = df_new[df_new[df_new.columns[11]]<q]

In [24]:
q = df_new[df_new.columns[10]].quantile(.98)
df_new = df_new[df_new[df_new.columns[10]]<q]

In [25]:
q = df_new[df_new.columns[8]].quantile(.98)
df_new = df_new[df_new[df_new.columns[8]]<q]

In [26]:
q = df_new[df_new.columns[12]].quantile(.99)
df_new = df_new[df_new[df_new.columns[12]]<q]

In [27]:
q = df_new[df_new.columns[1]].quantile(.99)
df_new = df_new[df_new[df_new.columns[1]]<q]

In [28]:
q = df_new[df_new.columns[2]].quantile(.99)
df_new = df_new[df_new[df_new.columns[2]]<q]

In [29]:
fig,ax = plt.subplots()
plt.figure(figsize=(40,80))
sns.boxplot(data = df_new, ax = ax)
plt.show()

In [30]:
df_new.shape

(6762, 14)

## Separating Independent and Dependent Variables

In [31]:
x = df_new.drop(columns="not.fully.paid")

In [32]:
y = df_new["not.fully.paid"]

## Train Test Split

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state= 22)

## Model Building

1) Logistic Regression

In [34]:
"""r = 500
l = []
for i in range(500):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state=i)
    xgb_model1 = LogisticRegression()
    xgb_model1.fit(x_train, y_train)
    test = xgb_model1.score(x_test, y_test)
    train = xgb_model1.score(x_train, y_train)
    if test > .7:
        l.append([test, train, i])"""

'r = 500\nl = []\nfor i in range(500):\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state=i)\n    xgb_model1 = LogisticRegression()\n    xgb_model1.fit(x_train, y_train)\n    test = xgb_model1.score(x_test, y_test)\n    train = xgb_model1.score(x_train, y_train)\n    if test > .7:\n        l.append([test, train, i])'

In [35]:
"""for i in l:
    if i[1] > .86:
        print(i)"""

'for i in l:\n    if i[1] > .86:\n        print(i)'

In [36]:
logistic = LogisticRegression()

In [37]:
logistic.fit(x_train, y_train)

LogisticRegression()

In [38]:
logistic.score(x_train, y_train)

0.8649904922881894

In [39]:
logistic.score(x_test, y_test)

0.8649581074420897

In [40]:
y_test_pred1 = logistic.predict(x_test)

In [41]:
print("Accuracy Score =", round(sm.accuracy_score(y_test, y_test_pred1), 2)) 
print("Precision Score =", sm.precision_score(y_test, y_test_pred1))
print("Confucion Matrix =\n", sm.confusion_matrix(y_test, y_test_pred1))
print("Recall Score =", sm.recall_score(y_test, y_test_pred1))
print("AUC Score =",sm. roc_auc_score(y_test, y_test_pred1))
print("Classification Report =\n", sm.classification_report(y_test, y_test_pred1))


Accuracy Score = 0.86
Precision Score = 1.0
Confucion Matrix =
 [[1753    0]
 [ 274    2]]
Recall Score = 0.007246376811594203
AUC Score = 0.5036231884057971
Classification Report =
               precision    recall  f1-score   support

           0       0.86      1.00      0.93      1753
           1       1.00      0.01      0.01       276

    accuracy                           0.86      2029
   macro avg       0.93      0.50      0.47      2029
weighted avg       0.88      0.86      0.80      2029



2) Decision Tree Classifier

In [42]:
tree = DecisionTreeClassifier()

In [43]:
tree.fit(x_train, y_train)

DecisionTreeClassifier()

In [44]:
tree.score(x_train, y_train)

1.0

In [45]:
tree.score(x_test, y_test)

0.7654016757023164

In [46]:
y_test_pred2 = tree.predict(x_test)

In [47]:
print("Accuracy Score =", round(sm.accuracy_score(y_test, y_test_pred2), 2)) 
print("Precision Score =", sm.precision_score(y_test, y_test_pred2))
print("Confucion Matrix =\n", sm.confusion_matrix(y_test, y_test_pred2))
print("Recall Score =", sm.recall_score(y_test, y_test_pred2))
print("AUC Score =", sm.roc_auc_score(y_test, y_test_pred2))
print("Classification Report =\n", sm.classification_report(y_test, y_test_pred2))


Accuracy Score = 0.77
Precision Score = 0.16216216216216217
Confucion Matrix =
 [[1505  248]
 [ 228   48]]
Recall Score = 0.17391304347826086
AUC Score = 0.5162206403928669
Classification Report =
               precision    recall  f1-score   support

           0       0.87      0.86      0.86      1753
           1       0.16      0.17      0.17       276

    accuracy                           0.77      2029
   macro avg       0.52      0.52      0.52      2029
weighted avg       0.77      0.77      0.77      2029



3) KNeighbors Classifier

In [48]:
"""mean_acc = np.zeros(20)
for i in range(1,21):
    #Train Model and Predict  
    knn = KNeighborsClassifier(n_neighbors = i).fit(x_train,y_train)
    yhat= knn.predict(x_test)
    mean_acc[i-1] = sm.accuracy_score(y_test, yhat)
mean_acc"""

'mean_acc = np.zeros(20)\nfor i in range(1,21):\n    #Train Model and Predict  \n    knn = KNeighborsClassifier(n_neighbors = i).fit(x_train,y_train)\n    yhat= knn.predict(x_test)\n    mean_acc[i-1] = sm.accuracy_score(y_test, yhat)\nmean_acc'

In [49]:
"""r = 500
l = []
for i in range(500):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state=i)
    xgb_model1 = KNeighborsClassifier()
    xgb_model1.fit(x_train, y_train)
    test = xgb_model1.score(x_test, y_test)
    train = xgb_model1.score(x_train, y_train)
    if test > .7:
        l.append([test, train, i])"""

'r = 500\nl = []\nfor i in range(500):\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state=i)\n    xgb_model1 = KNeighborsClassifier()\n    xgb_model1.fit(x_train, y_train)\n    test = xgb_model1.score(x_test, y_test)\n    train = xgb_model1.score(x_train, y_train)\n    if test > .7:\n        l.append([test, train, i])'

In [50]:
"""for i in l:
    if i[0] > .84:
        print(i)"""

'for i in l:\n    if i[0] > .84:\n        print(i)'

In [51]:
KNN = KNeighborsClassifier(n_neighbors=18)

In [52]:
KNN.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=18)

In [53]:
KNN.score(x_train, y_train)

0.8654130572575534

In [54]:
KNN.score(x_test, y_test)

0.8639724001971415

In [55]:
y_test_pred3 = KNN.predict(x_test)

In [56]:
print("Accuracy Score =", round(sm.accuracy_score(y_test, y_test_pred3), 2)) 
print("Precision Score =", sm.precision_score(y_test, y_test_pred3))
print("Confucion Matrix =\n", sm.confusion_matrix(y_test, y_test_pred3))
print("Recall Score =", sm.recall_score(y_test, y_test_pred3))
print("AUC Score =", sm.roc_auc_score(y_test, y_test_pred3))
print("Classification Report =\n", sm.classification_report(y_test, y_test_pred3))


Accuracy Score = 0.86
Precision Score = 0.0
Confucion Matrix =
 [[1753    0]
 [ 276    0]]
Recall Score = 0.0
AUC Score = 0.5
Classification Report =
               precision    recall  f1-score   support

           0       0.86      1.00      0.93      1753
           1       0.00      0.00      0.00       276

    accuracy                           0.86      2029
   macro avg       0.43      0.50      0.46      2029
weighted avg       0.75      0.86      0.80      2029



C:\Users\yadav\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\yadav\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\yadav\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\yadav\AppData

4) Random Forest Classifier

In [57]:
random = RandomForestClassifier()

In [58]:
random.fit(x_train, y_train)

RandomForestClassifier()

In [59]:
random.score(x_train, y_train)

1.0

In [60]:
random.score(x_test, y_test)

0.8629866929521932

In [61]:
y_test_pred4 = random.predict(x_test)

In [62]:
print("Accuracy Score =", round(sm.accuracy_score(y_test, y_test_pred4), 2)) 
print("Precision Score =", sm.precision_score(y_test, y_test_pred4))
print("Confucion Matrix =\n", sm.confusion_matrix(y_test, y_test_pred4))
print("Recall Score =", sm.recall_score(y_test, y_test_pred4))
print("AUC Score =", sm.roc_auc_score(y_test, y_test_pred4))
print("Classification Report =\n", sm.classification_report(y_test, y_test_pred4))

Accuracy Score = 0.86
Precision Score = 0.3333333333333333
Confucion Matrix =
 [[1749    4]
 [ 274    2]]
Recall Score = 0.007246376811594203
AUC Score = 0.5024822870937605
Classification Report =
               precision    recall  f1-score   support

           0       0.86      1.00      0.93      1753
           1       0.33      0.01      0.01       276

    accuracy                           0.86      2029
   macro avg       0.60      0.50      0.47      2029
weighted avg       0.79      0.86      0.80      2029



## Finalizing Model and Save into Pickle File

In [63]:
pickle.dump(logistic, open("Loan_model.pkl", "wb"))